const PROJECT_MANAGER_PERMISSIONS = [
  "PROJECT_VIEW",
  "PROJECT_CREATE",
  "PROJECT_UPDATE",
  "PROJECT_DELETE",
  "PROJECT_MANAGE_MEMBERS",
];

const TEAM_MANAGER_PERMISSIONS = ["TEAM_VIEW", "TEAM_CREATE", "TEAM_UPDATE", "TEAM_MANAGE_MEMBERS"];

// These defaults are applied at authentication time. They are needed for
// accounts created before role-permission records are synchronized onto the
// user document (including self-registered Manager accounts).
const TASK_MANAGER_PERMISSIONS = [
  "TASK_VIEW",
  "TASK_CREATE",
  "TASK_UPDATE",
  "TASK_DELETE",
  "TASK_ASSIGN",
  "TASK_REASSIGN",
  "TASK_CLOSE",
];

// Task matrix defaults. Reassign and close are intentionally not inferred for
// these roles because their assignments are not specified by the matrix.
const PROJECT_MANAGER_TASK_PERMISSIONS = ["TASK_VIEW", "TASK_CREATE", "TASK_UPDATE", "TASK_DELETE", "TASK_ASSIGN"];
const TEAM_LEAD_TASK_PERMISSIONS = ["TASK_VIEW", "TASK_CREATE", "TASK_UPDATE", "TASK_ASSIGN"];
const TASK_CONTRIBUTOR_PERMISSIONS = ["TASK_VIEW", "TASK_UPDATE"];

const ADMIN_TASK_PERMISSIONS = ["TASK_VIEW", "TASK_CREATE", "TASK_UPDATE", "TASK_DELETE"];

const rolePermissionDefaults = {
  SUPER_ADMIN: [
    ...PROJECT_MANAGER_PERMISSIONS,
    ...TEAM_MANAGER_PERMISSIONS,
    ...TASK_MANAGER_PERMISSIONS,
    "TEAM_DELETE",
    "USER_CREATE",
    "USER_VIEW",
    "USER_UPDATE",
    "USER_DELETE",
    "USER_ACTIVATE",
    "USER_DEACTIVATE",
    "ROLE_CREATE",
    "ROLE_VIEW",
    "ROLE_UPDATE",
    "ROLE_DELETE",
    "REPORT_VIEW",
    "REPORT_EXPORT",
    "DASHBOARD_VIEW",
    "DASHBOARD_CONFIGURE",
    "AUDIT_VIEW",
    "AUDIT_EXPORT",
  ],
  ADMIN: [...PROJECT_MANAGER_PERMISSIONS, ...TEAM_MANAGER_PERMISSIONS, ...ADMIN_TASK_PERMISSIONS, "TEAM_DELETE"],
  COMPANY_ADMIN: [
    ...PROJECT_MANAGER_PERMISSIONS,
    ...TEAM_MANAGER_PERMISSIONS,
    ...TASK_MANAGER_PERMISSIONS,
    "TEAM_DELETE",
    "USER_CREATE",
    "USER_VIEW",
    "USER_UPDATE",
    "USER_DELETE",
    "REPORT_VIEW",
    "REPORT_EXPORT",
    "DASHBOARD_VIEW",
    "DASHBOARD_CONFIGURE",
  ],
  ORGANIZATION_ADMIN: [...PROJECT_MANAGER_PERMISSIONS, ...TEAM_MANAGER_PERMISSIONS, ...TASK_MANAGER_PERMISSIONS, "TEAM_DELETE"],
  MANAGER: [...PROJECT_MANAGER_PERMISSIONS, ...TEAM_MANAGER_PERMISSIONS, ...TASK_MANAGER_PERMISSIONS, "USER_CREATE", "USER_VIEW", "USER_UPDATE"],
  LEAD: TEAM_MANAGER_PERMISSIONS,
  PROJECT_MANAGER: [...PROJECT_MANAGER_PERMISSIONS, ...PROJECT_MANAGER_TASK_PERMISSIONS],
  TEAM_LEAD: [...TEAM_MANAGER_PERMISSIONS, ...TEAM_LEAD_TASK_PERMISSIONS],
  SENIOR_DEVELOPER: TASK_CONTRIBUTOR_PERMISSIONS,
  DEVELOPER: TASK_CONTRIBUTOR_PERMISSIONS,
  QA_ENGINEER: TASK_CONTRIBUTOR_PERMISSIONS,
  EMPLOYEE: [...TASK_CONTRIBUTOR_PERMISSIONS, "PROJECT_VIEW", "DASHBOARD_VIEW"],
  USER: [...TASK_CONTRIBUTOR_PERMISSIONS, "PROJECT_VIEW", "DASHBOARD_VIEW"],
  INTERN: TASK_CONTRIBUTOR_PERMISSIONS,
};

const getEffectivePermissions = (user = {}) => {
  const assignedPermissions = Array.isArray(user.permissions) ? user.permissions : [];
  const role = String(user.role || "").trim().toUpperCase();
  return [...new Set([...assignedPermissions, ...(rolePermissionDefaults[role] || [])])];
};

module.exports = {
  PROJECT_MANAGER_PERMISSIONS,
  TEAM_MANAGER_PERMISSIONS,
  TASK_MANAGER_PERMISSIONS,
  PROJECT_MANAGER_TASK_PERMISSIONS,
  TEAM_LEAD_TASK_PERMISSIONS,
  TASK_CONTRIBUTOR_PERMISSIONS,
  getEffectivePermissions,
};
